# Streamlit Cloud secrets
# Cách lấy folder ID:
# 1. Mở folder trên Google Drive
# 2. URL sẽ có dạng: https://drive.google.com/drive/folders/ABC123XYZ
# 3. Copy phần "ABC123XYZ" → đó là folder ID

GOLD_FOLDER_ID = "17O8OmF4WZA7Xeu062Mam_GdL6DcSfdIo"
SILVER_FOLDER_ID = "1BNVjYXGLrH0IAH9WvRXv3QtmwyQzrYim"
